In [4]:
import pandas as pd

In [7]:
data= { 'Students':['Amit','Anam','Chi','Sam','Ravi','Jai'],'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(data)
df

  Students  Marks
0     Amit   85.0
1     Anam    NaN
2      Chi   65.0
3      Sam   75.0
4     Ravi    NaN
5      Jai   55.0

In [8]:
print("Missing_Data")
print("Number of Missing values are:",df.isnull().sum())

Missing_Data
Number of Missing values are: Students    0
Marks       2
dtype: int64

In [9]:
average_marks=df["Marks"].mean()
print(average_marks)

70.0

In [10]:
df.fillna(average_marks, inplace=True)

In [11]:
print("after fillna() call")
df

after fillna() call

  Students  Marks
0     Amit   85.0
1     Anam   70.0
2      Chi   65.0
3      Sam   75.0
4     Ravi   70.0
5      Jai   55.0

## Let us see it, how we will use in our project

In [16]:
students_data= { 'Students':['Amit','Anam','Chi','Sam','Ravi','Jai'],'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
print('Original Data')
df

Original Data

  Students  Marks
0     Amit   85.0
1     Anam    NaN
2      Chi   65.0
3      Sam   75.0
4     Ravi    NaN
5      Jai   55.0

In [17]:
df.fillna(df['Marks'].mean(),inplace=True)
print('After fillna:')
df

After fillna:

  Students  Marks
0     Amit   85.0
1     Anam   70.0
2      Chi   65.0
3      Sam   75.0
4     Ravi   70.0
5      Jai   55.0

In [19]:
students_data= { 'Students':['Amit','Anam','Chi','Sam','Ravi','Jai'],'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
df=df.dropna()
print("Datasets after dropna()")
df

Datasets after dropna

  Students  Marks
0     Amit   85.0
2      Chi   65.0
3      Sam   75.0
5      Jai   55.0

In [35]:
emp_data={
    "Name":['Sam','Ali','Chang','Xi','Viz','Suhaili'],
    "Age":[35,None,25,20,24,None],
    "Salary":[50000,30000,20000,40000,None,None],
}
df=pd.DataFrame(emp_data)
df

      Name   Age   Salary
0      Sam  35.0  50000.0
1      Ali   NaN  30000.0
2    Chang  25.0  20000.0
3       Xi  20.0  40000.0
4      Viz  24.0      NaN
5  Suhaili   NaN      NaN

In [36]:
print(df.isnull().sum())

Name      0
Age       2
Salary    2
dtype: int64

In [37]:
df_drop=df.dropna()
df_drop

    Name   Age   Salary
0    Sam  35.0  50000.0
2  Chang  25.0  20000.0
3     Xi  20.0  40000.0

In [38]:
df_drop_salary=df.dropna(subset=['Salary'])
df_drop_salary

    Name   Age   Salary
0    Sam  35.0  50000.0
1    Ali   NaN  30000.0
2  Chang  25.0  20000.0
3     Xi  20.0  40000.0

In [48]:
#fillna example
emp_data={
    "Name":['Sam','Ali','Chang','Xi','Viz','Suhaili'],
    "Age":[35,None,25,20,24,None],
    "Salary":[50000,30000,20000,40000,None,None],
}
df=pd.DataFrame(emp_data)
df.fillna({'Age':df['Age'].mean(),'Salary':df['Salary'].mean()},inplace=True)
df

      Name   Age   Salary
0      Sam  35.0  50000.0
1      Ali  26.0  30000.0
2    Chang  25.0  20000.0
3       Xi  20.0  40000.0
4      Viz  24.0  35000.0
5  Suhaili  26.0  35000.0

Number of Missing Values are: gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

# download students_performance_dirty.csv
## find out number of missing data
## drop rows where gender is missing
## fill study_hours with average_study_hours

In [112]:
## Solution1: find out number of missing data
df=pd.read_csv("students_performance_dirty.csv")
df.head()
print('Number of Missing Values are:',df.isnull().sum())

Number of Missing Values are: gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [126]:
## Solution2: drop rows where gender is missing
df.dropna(subset=['gender'],inplace=True)
df

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.7,83.6,62.0,91.0,38.9
2,female,2.9,97.5,69.0,57.0,35.0
3,female,4.8,85.7,78.0,62.0,36.5
4,male,3.9,-10.0,64.0,95.0,30.9
5,male,1.4,93.7,77.0,72.0,39.0
6,male,NaN,87.1,95.0,78.0,43.4
7,femle,NaN,70.6,59.0,70.0,32.8
8,female,2.7,74.7,68.0,71.0,35.3
9,female,4.2,92.4,63.0,66.0,35.0
10,male,4.7,67.9,94.0,73.0,40.1
12,femle,NaN,95.0,59.0,92.0,39.7
13,male,NaN,86.5,61.0,50.0,30.8
14,male,3.9,79.0,68.0,91.0,39.8
15,male,4.7,76.5,58.0,78.0,34.9
16,male,2.9,93.2,64.0,68.0,35.7
17,female,3.3,89.7,72.0,65.0,36.5
18,female,2.2,150.0,68.0,85.0,45.6
19,male,2.1,95.7,82.0,75.0,41.0
20,female,NaN,93.5,65.0,54.0,33.1
21,male,5.1,102.9,67.0,76.0,38.9
22,male,3.4,90.7,74.0,86.0,41.0
23,male,4.7,83.4,104.0,82.0,45.5
24,female,3.9,83.6,58.0,64.0,32.9
25,female,2.7,65.7,99.0,56.0,37.5
26,male,3.9,86.5,52.0,68.0,32.7
27,female,5.3,84.8,73.0,111.0,45.4
28,female,NaN,71.7,65.0,53.0,30.8
29,male,5.4,84.7,58.0,62.0,32.4
30,female,0.4,98.4,80.0,77.0,41.3
31,male,4.5,77.7,79.0,71.0,37.7
32,male,3.6,75.4,63.0,70.0,34.0
35,femle,1.1,115.6,72.0,72.0,40.3
36,male,3.2,71.8,70.0,74.0,36.1
37,male,3.9,92.2,81.0,62.0,38.0
38,female,5.3,88.2,99.0,55.0,39.6
39,female,2.9,85.6,76.0,75.0,38.8
40,male,2.5,94.1,79.0,94.0,43.9
41,female,2.9,84.7,72.0,77.0,38.3
42,male,4.6,65.6,88.0,73.0,38.7
44,male,2.9,200.0,81.0,69.0,50.0
45,female,4.1,96.7,97.0,86.0,46.3
46,male,3.6,81.3,73.0,66.0,36.0
47,female,4.7,90.0,66.0,56.0,33.3
48,female,2.7,112.8,77.0,53.0,37.2
49,male,3.1,84.7,87.0,73.0,40.5
51,female,1.7,86.9,86.0,75.0,40.8
53,femle,3.8,81.5,57.0,78.0,35.0
54,female,3.5,91.1,62.0,74.0,36.3
56,male,1.8,88.4,72.0,88.0,40.8
57,male,3.0,85.5,64.0,61.0,33.4
58,male,3.1,82.8,88.0,44.0,34.8
59,male,NaN,80.2,51.0,68.0,31.7

In [127]:
## Solution3: fill study_hours with average_study_hours
df.fillna({'study_hours':df['study_hours'].mean()},inplace=True)
df

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.700000,83.6,62.0,91.0,38.9
2,female,2.900000,97.5,69.0,57.0,35.0
3,female,4.800000,85.7,78.0,62.0,36.5
4,male,3.900000,-10.0,64.0,95.0,30.9
5,male,1.400000,93.7,77.0,72.0,39.0
6,male,3.393333,87.1,95.0,78.0,43.4
7,femle,3.393333,70.6,59.0,70.0,32.8
8,female,2.700000,74.7,68.0,71.0,35.3
9,female,4.200000,92.4,63.0,66.0,35.0
10,male,4.700000,67.9,94.0,73.0,40.1
12,femle,3.393333,95.0,59.0,92.0,39.7
13,male,3.393333,86.5,61.0,50.0,30.8
14,male,3.900000,79.0,68.0,91.0,39.8
15,male,4.700000,76.5,58.0,78.0,34.9
16,male,2.900000,93.2,64.0,68.0,35.7
17,female,3.300000,89.7,72.0,65.0,36.5
18,female,2.200000,150.0,68.0,85.0,45.6
19,male,2.100000,95.7,82.0,75.0,41.0
20,female,3.393333,93.5,65.0,54.0,33.1
21,male,5.100000,102.9,67.0,76.0,38.9
22,male,3.400000,90.7,74.0,86.0,41.0
23,male,4.700000,83.4,104.0,82.0,45.5
24,female,3.900000,83.6,58.0,64.0,32.9
25,female,2.700000,65.7,99.0,56.0,37.5
26,male,3.900000,86.5,52.0,68.0,32.7
27,female,5.300000,84.8,73.0,111.0,45.4
28,female,3.393333,71.7,65.0,53.0,30.8
29,male,5.400000,84.7,58.0,62.0,32.4
30,female,0.400000,98.4,80.0,77.0,41.3
31,male,4.500000,77.7,79.0,71.0,37.7
32,male,3.600000,75.4,63.0,70.0,34.0
35,femle,1.100000,115.6,72.0,72.0,40.3
36,male,3.200000,71.8,70.0,74.0,36.1
37,male,3.900000,92.2,81.0,62.0,38.0
38,female,5.300000,88.2,99.0,55.0,39.6
39,female,2.900000,85.6,76.0,75.0,38.8
40,male,2.500000,94.1,79.0,94.0,43.9
41,female,2.900000,84.7,72.0,77.0,38.3
42,male,4.600000,65.6,88.0,73.0,38.7
44,male,2.900000,200.0,81.0,69.0,50.0
45,female,4.100000,96.7,97.0,86.0,46.3
46,male,3.600000,81.3,73.0,66.0,36.0
47,female,4.700000,90.0,66.0,56.0,33.3
48,female,2.700000,112.8,77.0,53.0,37.2
49,male,3.100000,84.7,87.0,73.0,40.5
51,female,1.700000,86.9,86.0,75.0,40.8
53,femle,3.800000,81.5,57.0,78.0,35.0
54,female,3.500000,91.1,62.0,74.0,36.3
56,male,1.800000,88.4,72.0,88.0,40.8
57,male,3.000000,85.5,64.0,61.0,33.4
58,male,3.100000,82.8,88.0,44.0,34.8
59,male,3.393333,80.2,51.0,68.0,31.7

In [137]:
## Solution1: find out number of missing data
df=pd.read_csv("students_performance_dirty.csv")
df.head()
print('Number of Missing Values are:',df.isnull().sum())
rows, cols = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

## Solution2: drop rows where gender is missing
df.dropna(subset=['gender'],inplace=True)
#df is updated with no missing gender values

## Solution3: fill study_hours with average_study_hours
df.fillna({'study_hours':df['study_hours'].mean()},inplace=True)
#df is replaced with average study hours

rows, cols = df.shape
print("After cleaning:")
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

df

Number of Missing Values are: gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64
Number of rows: 60
Number of columns: 6
After cleaning:
Number of rows: 52
Number of columns: 6

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.700000,83.6,62.0,91.0,38.9
2,female,2.900000,97.5,69.0,57.0,35.0
3,female,4.800000,85.7,78.0,62.0,36.5
4,male,3.900000,-10.0,64.0,95.0,30.9
5,male,1.400000,93.7,77.0,72.0,39.0
6,male,3.393333,87.1,95.0,78.0,43.4
7,femle,3.393333,70.6,59.0,70.0,32.8
8,female,2.700000,74.7,68.0,71.0,35.3
9,female,4.200000,92.4,63.0,66.0,35.0
10,male,4.700000,67.9,94.0,73.0,40.1
12,femle,3.393333,95.0,59.0,92.0,39.7
13,male,3.393333,86.5,61.0,50.0,30.8
14,male,3.900000,79.0,68.0,91.0,39.8
15,male,4.700000,76.5,58.0,78.0,34.9
16,male,2.900000,93.2,64.0,68.0,35.7
17,female,3.300000,89.7,72.0,65.0,36.5
18,female,2.200000,150.0,68.0,85.0,45.6
19,male,2.100000,95.7,82.0,75.0,41.0
20,female,3.393333,93.5,65.0,54.0,33.1
21,male,5.100000,102.9,67.0,76.0,38.9
22,male,3.400000,90.7,74.0,86.0,41.0
23,male,4.700000,83.4,104.0,82.0,45.5
24,female,3.900000,83.6,58.0,64.0,32.9
25,female,2.700000,65.7,99.0,56.0,37.5
26,male,3.900000,86.5,52.0,68.0,32.7
27,female,5.300000,84.8,73.0,111.0,45.4
28,female,3.393333,71.7,65.0,53.0,30.8
29,male,5.400000,84.7,58.0,62.0,32.4
30,female,0.400000,98.4,80.0,77.0,41.3
31,male,4.500000,77.7,79.0,71.0,37.7
32,male,3.600000,75.4,63.0,70.0,34.0
35,femle,1.100000,115.6,72.0,72.0,40.3
36,male,3.200000,71.8,70.0,74.0,36.1
37,male,3.900000,92.2,81.0,62.0,38.0
38,female,5.300000,88.2,99.0,55.0,39.6
39,female,2.900000,85.6,76.0,75.0,38.8
40,male,2.500000,94.1,79.0,94.0,43.9
41,female,2.900000,84.7,72.0,77.0,38.3
42,male,4.600000,65.6,88.0,73.0,38.7
44,male,2.900000,200.0,81.0,69.0,50.0
45,female,4.100000,96.7,97.0,86.0,46.3
46,male,3.600000,81.3,73.0,66.0,36.0
47,female,4.700000,90.0,66.0,56.0,33.3
48,female,2.700000,112.8,77.0,53.0,37.2
49,male,3.100000,84.7,87.0,73.0,40.5
51,female,1.700000,86.9,86.0,75.0,40.8
53,femle,3.800000,81.5,57.0,78.0,35.0
54,female,3.500000,91.1,62.0,74.0,36.3
56,male,1.800000,88.4,72.0,88.0,40.8
57,male,3.000000,85.5,64.0,61.0,33.4
58,male,3.100000,82.8,88.0,44.0,34.8
59,male,3.393333,80.2,51.0,68.0,31.7