

## 3. Linear Regression Model
## 4. Feature Engg.
## 5. Tuning
## 6. Cross Validation
## 7. Residual Analysis

In [249]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import math

In [250]:
data = {
    'StudyHours': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Attendance': [60, 65, 70, 72, 75, 80, 85, 88, 90],
    'PrevScore': [40, 45, 50, 55, 60, 65, 70, 75, 80],
    'FinalMarks': [50, 55, 60, 65, 70, 75, 78, 85, 88]
}

df = pd.DataFrame (data)
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [251]:
y = df['FinalMarks']
y

0    50
1    55
2    60
3    65
4    70
5    75
6    78
7    85
8    88
Name: FinalMarks, dtype: int64

In [252]:
y_pred_baseline = np.repeat(y.mean(),len(y))
y_pred_baseline

array([69.55555556, 69.55555556, 69.55555556, 69.55555556, 69.55555556,
       69.55555556, 69.55555556, 69.55555556, 69.55555556])

In [253]:
mae = mean_absolute_error(y,y_pred_baseline)
print(mae)

10.716049382716049

In [254]:
mse = mean_squared_error(y,y_pred_baseline)
print(mse)

154.02469135802468

In [255]:
rmse = np.sqrt(mse)
print(rmse)

12.410668449282847

In [256]:
r2 = r2_score(y,y_pred_baseline)
print(f'Baseline MAE = {mae:.2f},RMSE = {rmse:.2f}, R-squared = {r2:.2f}')

Baseline MAE = 10.72,RMSE = 12.41, R-squared = 0.00

In [257]:
# Clean the data

print(df.isnull().sum())

StudyHours    0
Attendance    0
PrevScore     0
FinalMarks    0
dtype: int64

In [258]:
df=df.fillna(df.mean())

In [259]:
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [260]:
# Data prep, find input, output
x = df[['StudyHours','Attendance','PrevScore']]
y = df['FinalMarks']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [261]:
# model creation
model = LinearRegression()

In [262]:
model.fit(x_train,y_train)

LinearRegression()

In [263]:
## just for reference
y_model_test = model.predict(x)

new_col = pd.DataFrame({'y_model_test' : [50.65945946, 55.16756757, 59.67567568, 64.62162162, 69.42162162, 73.92972973,
 78.43783784, 83.23783784, 88.18378378]})
df_withpred = pd.concat([df,round(new_col,2)],axis=1)
df_withpred

   StudyHours  Attendance  PrevScore  FinalMarks  y_model_test
0           2          60         40          50         50.66
1           3          65         45          55         55.17
2           4          70         50          60         59.68
3           5          72         55          65         64.62
4           6          75         60          70         69.42
5           7          80         65          75         73.93
6           8          85         70          78         78.44
7           9          88         75          85         83.24
8          10          90         80          88         88.18

In [264]:
y_pred = model.predict(x_test)
print(y_pred)

[83.49107143 55.25357143]

In [265]:
mae = mean_absolute_error(y_test,y_pred)
print(mae)

0.8812500000000085

In [266]:
mse = mean_squared_error(y_test,y_pred)
print(mse)

1.170581951530632

In [267]:
rmse = np.sqrt(mse)
print(rmse)

1.081934356387037

In [268]:
r2 = r2_score(y_test,y_pred)
print(f'Baseline MAE = {mae:.2f},RMSE = {rmse:.2f}, R-squared = {r2:.2f}')

Baseline MAE = 0.88,RMSE = 1.08, R-squared = 0.99

# Exercise
1. Base Line (mean prediction)
2. Data Cleaning & preparation
3. Linear Regression Model
4. Find out MAE, RMSE, R-Squared
5. Data set as follows
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = {
    'Area': [850,900,1000,1100,1200,1500,16000,1800,2000],
    'Bedrooms': [1,2,2,2,3,3,2,4,4],
    'PriceIn100K':[5,6,7,7,70,9,9,11,None] }

In [269]:
data = {
    'Area': [850,900,1000,1100,1200,1500,16000,1800,2000],
    'Bedrooms': [1,2,2,2,3,3,2,4,4],
    'Age': [1,1,3,2,1,2,2,1,2],
    'PriceIn100K':[5,6,7,7,70,9,9,11,None],
}

df = pd.DataFrame(data)
df

    Area  Bedrooms  Age  PriceIn100K
0    850         1    1          5.0
1    900         2    1          6.0
2   1000         2    3          7.0
3   1100         2    2          7.0
4   1200         3    1         70.0
5   1500         3    2          9.0
6  16000         2    2          9.0
7   1800         4    1         11.0
8   2000         4    2          NaN

In [270]:
# Clean the data

print(df.isnull().sum())

Area           0
Bedrooms       0
Age            0
PriceIn100K    1
dtype: int64

In [271]:
df=df.fillna(df.mean())
df

    Area  Bedrooms  Age  PriceIn100K
0    850         1    1          5.0
1    900         2    1          6.0
2   1000         2    3          7.0
3   1100         2    2          7.0
4   1200         3    1         70.0
5   1500         3    2          9.0
6  16000         2    2          9.0
7   1800         4    1         11.0
8   2000         4    2         15.5

In [272]:
# Data prep, find input, output
x = df[['Area','Bedrooms','Age']]
y = df['PriceIn100K']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [273]:
# model creation
model = LinearRegression()

In [274]:
model.fit(x_train,y_train)

LinearRegression()

In [275]:
## just for reference
y_model_test = model.predict(x)
print(y_model_test)
new_col = pd.DataFrame({'y_model_test' :[ 6.00427441, 14.82971343, 14.78445581, 14.73919818, 23.54200839, 23.40623552,
  7.99581244, 32.11853049, 32.02801524]})
df_withpred = pd.concat([df,round(new_col,2)],axis=1)
df_withpred

[19.33921653 29.81817484 -8.40782346 10.6786718  40.25296001 21.09578773
  8.045953   50.63473742 31.49523439]

    Area  Bedrooms  Age  PriceIn100K  y_model_test
0    850         1    1          5.0          6.00
1    900         2    1          6.0         14.83
2   1000         2    3          7.0         14.78
3   1100         2    2          7.0         14.74
4   1200         3    1         70.0         23.54
5   1500         3    2          9.0         23.41
6  16000         2    2          9.0          8.00
7   1800         4    1         11.0         32.12
8   2000         4    2         15.5         32.03

In [276]:
y_pred = model.predict(x_test)
print(y_pred)

[50.63473742 29.81817484]

In [277]:
mae = mean_absolute_error(y_test,y_pred)
print(mae)

31.72645612978434

In [278]:
mse = mean_squared_error(y_test,y_pred)
print(mse)

1069.1089315916172

In [279]:
rmse = np.sqrt(mse)
print(rmse)

32.69723125268587

In [280]:
r2 = r2_score(y_test,y_pred)
print(f'Baseline MAE = {mae:.2f},RMSE = {rmse:.2f}, R-squared = {r2:.2f}')

Baseline MAE = 31.73,RMSE = 32.70, R-squared = -170.06

# Answer from cgpt

In [285]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Data
data = {
    'Area': [850,900,1000,1100,1200,1500,16000,1800,2000],
    'Bedrooms': [1,2,2,2,3,3,2,4,4],
    'Age': [1,1,3,2,1,2,2,1,2],
    'PriceIn100K':[5,6,7,7,70,9,9,11,None]}

df = pd.DataFrame(data)
df = df.fillna(df.mean())

# Input & output
x = df[['Area','Bedrooms','Age']]
y = df['PriceIn100K']

# Split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Model
model = LinearRegression()
model.fit(x_train, y_train)

# Prediction
y_pred = model.predict(x_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f'MAE = {mae:.2f}, RMSE = {rmse:.2f}, R-squared = {r2:.2f}')

MAE = 31.73, RMSE = 32.70, R-squared = -170.06