In [1]:
import pandas as pd

In [4]:
# Sample dataset
data = {
    'Name': ['Ali','Sara','John', None, 'Mary'],
    'Age': [25, None, 30, 22, None],
    'City': ['KL','penang', None,'Johor','KL']
}

In [5]:
df = pd.DataFrame(data)
print('Original Dataframe:')
print(df)

Original Dataframe:
   Name   Age    City
0   Ali  25.0      KL
1  Sara   NaN  penang
2  John  30.0    None
3  None  22.0   Johor
4  Mary   NaN      KL

## check the missing values Row by Row

In [11]:
for index, row in df.iterrows():
    print(f'Row {index}:Missing = {row.isnull().any()}, Details = {row.isnull().to_dict()}')

Row 0:Missing = False, Details = {'Name': False, 'Age': False, 'City': False}
Row 1:Missing = True, Details = {'Name': False, 'Age': True, 'City': False}
Row 2:Missing = True, Details = {'Name': False, 'Age': False, 'City': True}
Row 3:Missing = True, Details = {'Name': True, 'Age': False, 'City': False}
Row 4:Missing = True, Details = {'Name': False, 'Age': True, 'City': False}

In [8]:
# show only rows with missing data
missing_rows = df[df.isnull().any(axis=1)]
print('Rows with missing data')
print(missing_rows)

Rows with missing data
   Name   Age    City
1  Sara   NaN  penang
2  John  30.0    None
3  None  22.0   Johor
4  Mary   NaN      KL

In [9]:
# Stimulate rows that would be dropped using dropna()
to_drop = df[df.isnull().any(axis=1)]
print('These rows will be dropped using dropna():')
print(to_drop)

These rows will be dropped using dropna():
   Name   Age    City
1  Sara   NaN  penang
2  John  30.0    None
3  None  22.0   Johor
4  Mary   NaN      KL

In [10]:
df_cleaned = df.dropna()
print('After dropna():')
print(df_cleaned)

After dropna():
  Name   Age City
0  Ali  25.0   KL

In [12]:
print('Before filling:')
print(df)

Before filling:
   Name   Age    City
0   Ali  25.0      KL
1  Sara   NaN  penang
2  John  30.0    None
3  None  22.0   Johor
4  Mary   NaN      KL

In [13]:
df_filled = df.fillna({
    'Name' : 'Unknown',
    'Age' : df['Age'].mean(),
    'City' : 'Not Available'
})

In [14]:
print('After filling:')
print(df_filled)

After filling:
      Name        Age           City
0      Ali  25.000000             KL
1     Sara  25.666667         penang
2     John  30.000000  Not Available
3  Unknown  22.000000          Johor
4     Mary  25.666667             KL

In [19]:
df_sfill = df.fillna({
    'Name' : 'Unknown',
    'Age' : round(df['Age'].mean(),2),
    'City' : 'Not Available'
})
print('If want to make data in 2 decimal places only')
print(df_sfill)

If want to make data in 2 decimal places only
      Name    Age           City
0      Ali  25.00             KL
1     Sara  25.67         penang
2     John  30.00  Not Available
3  Unknown  22.00          Johor
4     Mary  25.67             KL

In [20]:
import math

In [21]:
df_sfill = df.fillna({
    'Name' : 'Unknown',
    'Age' : math.floor(df['Age'].mean()),
    'City' : 'Not Available'
})
print('If want to make data without decimal places')
print(df_sfill)

If want to make data in 2 decimal places only
      Name   Age           City
0      Ali  25.0             KL
1     Sara  25.0         penang
2     John  30.0  Not Available
3  Unknown  22.0          Johor
4     Mary  25.0             KL

In [22]:
df_sfill = df.fillna({
    'Name' : 'Unknown',
    'Age' : int(df['Age'].mean()),
    'City' : 'Not Available'
})
print('If want to make data without decimal places')
print(df_sfill)

If want to make data without decimal places
      Name   Age           City
0      Ali  25.0             KL
1     Sara  25.0         penang
2     John  30.0  Not Available
3  Unknown  22.0          Johor
4     Mary  25.0             KL

## Data Cleaning Exercise
    Step 1:downlaod dataset from the given link in chat & print dataset
    Step 2: Get basic information about dataset
    Step 3: print('Missing values per column:')
    Step 4: Check missing data line by line
    Step 5: Drop missing rows (if any)
    Step 6: Fill missing values
    Step 7: Compare before and after

In [77]:
# step 1
df = pd.read_csv('students_performance_dirty.csv')
print('Dataset loaded successfully!')
df.head()

Dataset loaded successfully!

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

In [78]:
# step 2
print('----- Dataset info -----')
print(df.info())

----- Dataset info -----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          52 non-null     object
 1   study_hours     52 non-null     float64
 2   attendance_pct  60 non-null     float64
 3   math_score      60 non-null     float64
 4   reading_score   60 non-null     float64
 5   final_score     60 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.9+ KB
None

In [79]:
# step 3
print('Missing values per column:')
print(df.isnull().sum())

Missing values per column:
gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [80]:
# step 4
for index, row in df.iterrows():
    print(f'Row {index}:Missing = {row.isnull().any()}, Details = {row.isnull().to_dict()}')

Row 0:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 1:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 2:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 3:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 4:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 5:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 6:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 7:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 8:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 9:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 10:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 11:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 12:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 13:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 14:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 15:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 16:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 17:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 18:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 19:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 20:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 21:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 22:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 23:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 24:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 25:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 26:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 27:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 28:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 29:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 30:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 31:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 32:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 33:Missing = True, Details = {'gender': True, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 34:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 35:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 36:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 37:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 38:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 39:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 40:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 41:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 42:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 43:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 44:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 45:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 46:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 47:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 48:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 49:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 50:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 51:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 52:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 53:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 54:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 55:Missing = True, Details = {'gender': True, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 56:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 57:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 58:Missing = False, Details = {'gender': False, 'study_hours': False, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}
Row 59:Missing = True, Details = {'gender': False, 'study_hours': True, 'attendance_pct': False, 'math_score': False, 'reading_score': False, 'final_score': False}

In [82]:
# step 4
missing_rows = df[df.isnull().any(axis=1)]
print(missing_rows.to_string())

    gender  study_hours  attendance_pct  math_score  reading_score  final_score
1      NaN          2.6            91.2        82.0           60.0         37.5
6     male          NaN            87.1        95.0           78.0         43.4
7    femle          NaN            70.6        59.0           70.0         32.8
11     NaN          4.6            86.2        63.0           78.0         36.9
12   femle          NaN            95.0        59.0           92.0         39.7
13    male          NaN            86.5        61.0           50.0         30.8
20  female          NaN            93.5        65.0           54.0         33.1
28  female          NaN            71.7        65.0           53.0         30.8
33     NaN          NaN            96.0        39.0           96.0         36.6
34     NaN          3.6            91.3        64.0           62.0         34.2
43     NaN          3.9            76.5        78.0           73.0         37.8
50     NaN          3.0            84.9        78.0           85.0         40.9
52     NaN          3.9            91.1        60.0           68.0         34.7
55     NaN          3.2           300.0        51.0           82.0         56.6
59    male          NaN            80.2        51.0           68.0         31.7

In [86]:
# step 5
df_donedrop = df.dropna(subset='gender')

In [88]:
# step 6
print('Shape before drop:\t', df.shape)
print('Shape after drop:\t', df_donedrop.shape)

Shape before drop:	 (60, 6)
Shape after drop:	 (52, 6)

In [91]:
# step 7
print('Aside from dropna, the NA value can be replaced')
df_filled = df.fillna({
    'gender':'Unknown',
    'study_hours':df['study_hours'].mean()})
df_filled

,gender,study_hours,attendance_pct,math_score,reading_score,final_score
0,male,1.700000,83.6,62.0,91.0,38.9
1,Unknown,2.600000,91.2,82.0,60.0,37.5
2,female,2.900000,97.5,69.0,57.0,35.0
3,female,4.800000,85.7,78.0,62.0,36.5
4,male,3.900000,-10.0,64.0,95.0,30.9
5,male,1.400000,93.7,77.0,72.0,39.0
6,male,3.413462,87.1,95.0,78.0,43.4
7,femle,3.413462,70.6,59.0,70.0,32.8
8,female,2.700000,74.7,68.0,71.0,35.3
9,female,4.200000,92.4,63.0,66.0,35.0
10,male,4.700000,67.9,94.0,73.0,40.1
11,Unknown,4.600000,86.2,63.0,78.0,36.9
12,femle,3.413462,95.0,59.0,92.0,39.7
13,male,3.413462,86.5,61.0,50.0,30.8
14,male,3.900000,79.0,68.0,91.0,39.8
15,male,4.700000,76.5,58.0,78.0,34.9
16,male,2.900000,93.2,64.0,68.0,35.7
17,female,3.300000,89.7,72.0,65.0,36.5
18,female,2.200000,150.0,68.0,85.0,45.6
19,male,2.100000,95.7,82.0,75.0,41.0
20,female,3.413462,93.5,65.0,54.0,33.1
21,male,5.100000,102.9,67.0,76.0,38.9
22,male,3.400000,90.7,74.0,86.0,41.0
23,male,4.700000,83.4,104.0,82.0,45.5
24,female,3.900000,83.6,58.0,64.0,32.9
25,female,2.700000,65.7,99.0,56.0,37.5
26,male,3.900000,86.5,52.0,68.0,32.7
27,female,5.300000,84.8,73.0,111.0,45.4
28,female,3.413462,71.7,65.0,53.0,30.8
29,male,5.400000,84.7,58.0,62.0,32.4
30,female,0.400000,98.4,80.0,77.0,41.3
31,male,4.500000,77.7,79.0,71.0,37.7
32,male,3.600000,75.4,63.0,70.0,34.0
33,Unknown,3.413462,96.0,39.0,96.0,36.6
34,Unknown,3.600000,91.3,64.0,62.0,34.2
35,femle,1.100000,115.6,72.0,72.0,40.3
36,male,3.200000,71.8,70.0,74.0,36.1
37,male,3.900000,92.2,81.0,62.0,38.0
38,female,5.300000,88.2,99.0,55.0,39.6
39,female,2.900000,85.6,76.0,75.0,38.8
40,male,2.500000,94.1,79.0,94.0,43.9
41,female,2.900000,84.7,72.0,77.0,38.3
42,male,4.600000,65.6,88.0,73.0,38.7
43,Unknown,3.900000,76.5,78.0,73.0,37.8
44,male,2.900000,200.0,81.0,69.0,50.0
45,female,4.100000,96.7,97.0,86.0,46.3
46,male,3.600000,81.3,73.0,66.0,36.0
47,female,4.700000,90.0,66.0,56.0,33.3
48,female,2.700000,112.8,77.0,53.0,37.2
49,male,3.100000,84.7,87.0,73.0,40.5
50,Unknown,3.000000,84.9,78.0,85.0,40.9
51,female,1.700000,86.9,86.0,75.0,40.8
52,Unknown,3.900000,91.1,60.0,68.0,34.7
53,femle,3.800000,81.5,57.0,78.0,35.0
54,female,3.500000,91.1,62.0,74.0,36.3
55,Unknown,3.200000,300.0,51.0,82.0,56.6
56,male,1.800000,88.4,72.0,88.0,40.8
57,male,3.000000,85.5,64.0,61.0,33.4
58,male,3.100000,82.8,88.0,44.0,34.8
59,male,3.413462,80.2,51.0,68.0,31.7

In [94]:
# step 8
for i in range(len(df)):
    print(f'Row {i} Before: {df.iloc[i].to_dict()}')
    print(f'Row {i} After: {df_filled.iloc[i].to_dict()}')

Row 0 Before: {'gender': 'male', 'study_hours': 1.7, 'attendance_pct': 83.6, 'math_score': 62.0, 'reading_score': 91.0, 'final_score': 38.9}
Row 0 After: {'gender': 'male', 'study_hours': 1.7, 'attendance_pct': 83.6, 'math_score': 62.0, 'reading_score': 91.0, 'final_score': 38.9}
Row 1 Before: {'gender': nan, 'study_hours': 2.6, 'attendance_pct': 91.2, 'math_score': 82.0, 'reading_score': 60.0, 'final_score': 37.5}
Row 1 After: {'gender': 'Unknown', 'study_hours': 2.6, 'attendance_pct': 91.2, 'math_score': 82.0, 'reading_score': 60.0, 'final_score': 37.5}
Row 2 Before: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 97.5, 'math_score': 69.0, 'reading_score': 57.0, 'final_score': 35.0}
Row 2 After: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 97.5, 'math_score': 69.0, 'reading_score': 57.0, 'final_score': 35.0}
Row 3 Before: {'gender': 'female', 'study_hours': 4.8, 'attendance_pct': 85.7, 'math_score': 78.0, 'reading_score': 62.0, 'final_score': 36.5}
Row 3 After: {'gender': 'female', 'study_hours': 4.8, 'attendance_pct': 85.7, 'math_score': 78.0, 'reading_score': 62.0, 'final_score': 36.5}
Row 4 Before: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': -10.0, 'math_score': 64.0, 'reading_score': 95.0, 'final_score': 30.9}
Row 4 After: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': -10.0, 'math_score': 64.0, 'reading_score': 95.0, 'final_score': 30.9}
Row 5 Before: {'gender': 'male', 'study_hours': 1.4, 'attendance_pct': 93.7, 'math_score': 77.0, 'reading_score': 72.0, 'final_score': 39.0}
Row 5 After: {'gender': 'male', 'study_hours': 1.4, 'attendance_pct': 93.7, 'math_score': 77.0, 'reading_score': 72.0, 'final_score': 39.0}
Row 6 Before: {'gender': 'male', 'study_hours': nan, 'attendance_pct': 87.1, 'math_score': 95.0, 'reading_score': 78.0, 'final_score': 43.4}
Row 6 After: {'gender': 'male', 'study_hours': 3.4134615384615383, 'attendance_pct': 87.1, 'math_score': 95.0, 'reading_score': 78.0, 'final_score': 43.4}
Row 7 Before: {'gender': 'femle', 'study_hours': nan, 'attendance_pct': 70.6, 'math_score': 59.0, 'reading_score': 70.0, 'final_score': 32.8}
Row 7 After: {'gender': 'femle', 'study_hours': 3.4134615384615383, 'attendance_pct': 70.6, 'math_score': 59.0, 'reading_score': 70.0, 'final_score': 32.8}
Row 8 Before: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 74.7, 'math_score': 68.0, 'reading_score': 71.0, 'final_score': 35.3}
Row 8 After: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 74.7, 'math_score': 68.0, 'reading_score': 71.0, 'final_score': 35.3}
Row 9 Before: {'gender': 'female', 'study_hours': 4.2, 'attendance_pct': 92.4, 'math_score': 63.0, 'reading_score': 66.0, 'final_score': 35.0}
Row 9 After: {'gender': 'female', 'study_hours': 4.2, 'attendance_pct': 92.4, 'math_score': 63.0, 'reading_score': 66.0, 'final_score': 35.0}
Row 10 Before: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 67.9, 'math_score': 94.0, 'reading_score': 73.0, 'final_score': 40.1}
Row 10 After: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 67.9, 'math_score': 94.0, 'reading_score': 73.0, 'final_score': 40.1}
Row 11 Before: {'gender': nan, 'study_hours': 4.6, 'attendance_pct': 86.2, 'math_score': 63.0, 'reading_score': 78.0, 'final_score': 36.9}
Row 11 After: {'gender': 'Unknown', 'study_hours': 4.6, 'attendance_pct': 86.2, 'math_score': 63.0, 'reading_score': 78.0, 'final_score': 36.9}
Row 12 Before: {'gender': 'femle', 'study_hours': nan, 'attendance_pct': 95.0, 'math_score': 59.0, 'reading_score': 92.0, 'final_score': 39.7}
Row 12 After: {'gender': 'femle', 'study_hours': 3.4134615384615383, 'attendance_pct': 95.0, 'math_score': 59.0, 'reading_score': 92.0, 'final_score': 39.7}
Row 13 Before: {'gender': 'male', 'study_hours': nan, 'attendance_pct': 86.5, 'math_score': 61.0, 'reading_score': 50.0, 'final_score': 30.8}
Row 13 After: {'gender': 'male', 'study_hours': 3.4134615384615383, 'attendance_pct': 86.5, 'math_score': 61.0, 'reading_score': 50.0, 'final_score': 30.8}
Row 14 Before: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 79.0, 'math_score': 68.0, 'reading_score': 91.0, 'final_score': 39.8}
Row 14 After: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 79.0, 'math_score': 68.0, 'reading_score': 91.0, 'final_score': 39.8}
Row 15 Before: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 76.5, 'math_score': 58.0, 'reading_score': 78.0, 'final_score': 34.9}
Row 15 After: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 76.5, 'math_score': 58.0, 'reading_score': 78.0, 'final_score': 34.9}
Row 16 Before: {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 93.2, 'math_score': 64.0, 'reading_score': 68.0, 'final_score': 35.7}
Row 16 After: {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 93.2, 'math_score': 64.0, 'reading_score': 68.0, 'final_score': 35.7}
Row 17 Before: {'gender': 'female', 'study_hours': 3.3, 'attendance_pct': 89.7, 'math_score': 72.0, 'reading_score': 65.0, 'final_score': 36.5}
Row 17 After: {'gender': 'female', 'study_hours': 3.3, 'attendance_pct': 89.7, 'math_score': 72.0, 'reading_score': 65.0, 'final_score': 36.5}
Row 18 Before: {'gender': 'female', 'study_hours': 2.2, 'attendance_pct': 150.0, 'math_score': 68.0, 'reading_score': 85.0, 'final_score': 45.6}
Row 18 After: {'gender': 'female', 'study_hours': 2.2, 'attendance_pct': 150.0, 'math_score': 68.0, 'reading_score': 85.0, 'final_score': 45.6}
Row 19 Before: {'gender': 'male', 'study_hours': 2.1, 'attendance_pct': 95.7, 'math_score': 82.0, 'reading_score': 75.0, 'final_score': 41.0}
Row 19 After: {'gender': 'male', 'study_hours': 2.1, 'attendance_pct': 95.7, 'math_score': 82.0, 'reading_score': 75.0, 'final_score': 41.0}
Row 20 Before: {'gender': 'female', 'study_hours': nan, 'attendance_pct': 93.5, 'math_score': 65.0, 'reading_score': 54.0, 'final_score': 33.1}
Row 20 After: {'gender': 'female', 'study_hours': 3.4134615384615383, 'attendance_pct': 93.5, 'math_score': 65.0, 'reading_score': 54.0, 'final_score': 33.1}
Row 21 Before: {'gender': 'male', 'study_hours': 5.1, 'attendance_pct': 102.9, 'math_score': 67.0, 'reading_score': 76.0, 'final_score': 38.9}
Row 21 After: {'gender': 'male', 'study_hours': 5.1, 'attendance_pct': 102.9, 'math_score': 67.0, 'reading_score': 76.0, 'final_score': 38.9}
Row 22 Before: {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 90.7, 'math_score': 74.0, 'reading_score': 86.0, 'final_score': 41.0}
Row 22 After: {'gender': 'male', 'study_hours': 3.4, 'attendance_pct': 90.7, 'math_score': 74.0, 'reading_score': 86.0, 'final_score': 41.0}
Row 23 Before: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 83.4, 'math_score': 104.0, 'reading_score': 82.0, 'final_score': 45.5}
Row 23 After: {'gender': 'male', 'study_hours': 4.7, 'attendance_pct': 83.4, 'math_score': 104.0, 'reading_score': 82.0, 'final_score': 45.5}
Row 24 Before: {'gender': 'female', 'study_hours': 3.9, 'attendance_pct': 83.6, 'math_score': 58.0, 'reading_score': 64.0, 'final_score': 32.9}
Row 24 After: {'gender': 'female', 'study_hours': 3.9, 'attendance_pct': 83.6, 'math_score': 58.0, 'reading_score': 64.0, 'final_score': 32.9}
Row 25 Before: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 65.7, 'math_score': 99.0, 'reading_score': 56.0, 'final_score': 37.5}
Row 25 After: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 65.7, 'math_score': 99.0, 'reading_score': 56.0, 'final_score': 37.5}
Row 26 Before: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 86.5, 'math_score': 52.0, 'reading_score': 68.0, 'final_score': 32.7}
Row 26 After: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 86.5, 'math_score': 52.0, 'reading_score': 68.0, 'final_score': 32.7}
Row 27 Before: {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 84.8, 'math_score': 73.0, 'reading_score': 111.0, 'final_score': 45.4}
Row 27 After: {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 84.8, 'math_score': 73.0, 'reading_score': 111.0, 'final_score': 45.4}
Row 28 Before: {'gender': 'female', 'study_hours': nan, 'attendance_pct': 71.7, 'math_score': 65.0, 'reading_score': 53.0, 'final_score': 30.8}
Row 28 After: {'gender': 'female', 'study_hours': 3.4134615384615383, 'attendance_pct': 71.7, 'math_score': 65.0, 'reading_score': 53.0, 'final_score': 30.8}
Row 29 Before: {'gender': 'male', 'study_hours': 5.4, 'attendance_pct': 84.7, 'math_score': 58.0, 'reading_score': 62.0, 'final_score': 32.4}
Row 29 After: {'gender': 'male', 'study_hours': 5.4, 'attendance_pct': 84.7, 'math_score': 58.0, 'reading_score': 62.0, 'final_score': 32.4}
Row 30 Before: {'gender': 'female', 'study_hours': 0.4, 'attendance_pct': 98.4, 'math_score': 80.0, 'reading_score': 77.0, 'final_score': 41.3}
Row 30 After: {'gender': 'female', 'study_hours': 0.4, 'attendance_pct': 98.4, 'math_score': 80.0, 'reading_score': 77.0, 'final_score': 41.3}
Row 31 Before: {'gender': 'male', 'study_hours': 4.5, 'attendance_pct': 77.7, 'math_score': 79.0, 'reading_score': 71.0, 'final_score': 37.7}
Row 31 After: {'gender': 'male', 'study_hours': 4.5, 'attendance_pct': 77.7, 'math_score': 79.0, 'reading_score': 71.0, 'final_score': 37.7}
Row 32 Before: {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 75.4, 'math_score': 63.0, 'reading_score': 70.0, 'final_score': 34.0}
Row 32 After: {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 75.4, 'math_score': 63.0, 'reading_score': 70.0, 'final_score': 34.0}
Row 33 Before: {'gender': nan, 'study_hours': nan, 'attendance_pct': 96.0, 'math_score': 39.0, 'reading_score': 96.0, 'final_score': 36.6}
Row 33 After: {'gender': 'Unknown', 'study_hours': 3.4134615384615383, 'attendance_pct': 96.0, 'math_score': 39.0, 'reading_score': 96.0, 'final_score': 36.6}
Row 34 Before: {'gender': nan, 'study_hours': 3.6, 'attendance_pct': 91.3, 'math_score': 64.0, 'reading_score': 62.0, 'final_score': 34.2}
Row 34 After: {'gender': 'Unknown', 'study_hours': 3.6, 'attendance_pct': 91.3, 'math_score': 64.0, 'reading_score': 62.0, 'final_score': 34.2}
Row 35 Before: {'gender': 'femle', 'study_hours': 1.1, 'attendance_pct': 115.6, 'math_score': 72.0, 'reading_score': 72.0, 'final_score': 40.3}
Row 35 After: {'gender': 'femle', 'study_hours': 1.1, 'attendance_pct': 115.6, 'math_score': 72.0, 'reading_score': 72.0, 'final_score': 40.3}
Row 36 Before: {'gender': 'male', 'study_hours': 3.2, 'attendance_pct': 71.8, 'math_score': 70.0, 'reading_score': 74.0, 'final_score': 36.1}
Row 36 After: {'gender': 'male', 'study_hours': 3.2, 'attendance_pct': 71.8, 'math_score': 70.0, 'reading_score': 74.0, 'final_score': 36.1}
Row 37 Before: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 92.2, 'math_score': 81.0, 'reading_score': 62.0, 'final_score': 38.0}
Row 37 After: {'gender': 'male', 'study_hours': 3.9, 'attendance_pct': 92.2, 'math_score': 81.0, 'reading_score': 62.0, 'final_score': 38.0}
Row 38 Before: {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 88.2, 'math_score': 99.0, 'reading_score': 55.0, 'final_score': 39.6}
Row 38 After: {'gender': 'female', 'study_hours': 5.3, 'attendance_pct': 88.2, 'math_score': 99.0, 'reading_score': 55.0, 'final_score': 39.6}
Row 39 Before: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 85.6, 'math_score': 76.0, 'reading_score': 75.0, 'final_score': 38.8}
Row 39 After: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 85.6, 'math_score': 76.0, 'reading_score': 75.0, 'final_score': 38.8}
Row 40 Before: {'gender': 'male', 'study_hours': 2.5, 'attendance_pct': 94.1, 'math_score': 79.0, 'reading_score': 94.0, 'final_score': 43.9}
Row 40 After: {'gender': 'male', 'study_hours': 2.5, 'attendance_pct': 94.1, 'math_score': 79.0, 'reading_score': 94.0, 'final_score': 43.9}
Row 41 Before: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 84.7, 'math_score': 72.0, 'reading_score': 77.0, 'final_score': 38.3}
Row 41 After: {'gender': 'female', 'study_hours': 2.9, 'attendance_pct': 84.7, 'math_score': 72.0, 'reading_score': 77.0, 'final_score': 38.3}
Row 42 Before: {'gender': 'male', 'study_hours': 4.6, 'attendance_pct': 65.6, 'math_score': 88.0, 'reading_score': 73.0, 'final_score': 38.7}
Row 42 After: {'gender': 'male', 'study_hours': 4.6, 'attendance_pct': 65.6, 'math_score': 88.0, 'reading_score': 73.0, 'final_score': 38.7}
Row 43 Before: {'gender': nan, 'study_hours': 3.9, 'attendance_pct': 76.5, 'math_score': 78.0, 'reading_score': 73.0, 'final_score': 37.8}
Row 43 After: {'gender': 'Unknown', 'study_hours': 3.9, 'attendance_pct': 76.5, 'math_score': 78.0, 'reading_score': 73.0, 'final_score': 37.8}
Row 44 Before: {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 200.0, 'math_score': 81.0, 'reading_score': 69.0, 'final_score': 50.0}
Row 44 After: {'gender': 'male', 'study_hours': 2.9, 'attendance_pct': 200.0, 'math_score': 81.0, 'reading_score': 69.0, 'final_score': 50.0}
Row 45 Before: {'gender': 'female', 'study_hours': 4.1, 'attendance_pct': 96.7, 'math_score': 97.0, 'reading_score': 86.0, 'final_score': 46.3}
Row 45 After: {'gender': 'female', 'study_hours': 4.1, 'attendance_pct': 96.7, 'math_score': 97.0, 'reading_score': 86.0, 'final_score': 46.3}
Row 46 Before: {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 81.3, 'math_score': 73.0, 'reading_score': 66.0, 'final_score': 36.0}
Row 46 After: {'gender': 'male', 'study_hours': 3.6, 'attendance_pct': 81.3, 'math_score': 73.0, 'reading_score': 66.0, 'final_score': 36.0}
Row 47 Before: {'gender': 'female', 'study_hours': 4.7, 'attendance_pct': 90.0, 'math_score': 66.0, 'reading_score': 56.0, 'final_score': 33.3}
Row 47 After: {'gender': 'female', 'study_hours': 4.7, 'attendance_pct': 90.0, 'math_score': 66.0, 'reading_score': 56.0, 'final_score': 33.3}
Row 48 Before: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 112.8, 'math_score': 77.0, 'reading_score': 53.0, 'final_score': 37.2}
Row 48 After: {'gender': 'female', 'study_hours': 2.7, 'attendance_pct': 112.8, 'math_score': 77.0, 'reading_score': 53.0, 'final_score': 37.2}
Row 49 Before: {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 84.7, 'math_score': 87.0, 'reading_score': 73.0, 'final_score': 40.5}
Row 49 After: {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 84.7, 'math_score': 87.0, 'reading_score': 73.0, 'final_score': 40.5}
Row 50 Before: {'gender': nan, 'study_hours': 3.0, 'attendance_pct': 84.9, 'math_score': 78.0, 'reading_score': 85.0, 'final_score': 40.9}
Row 50 After: {'gender': 'Unknown', 'study_hours': 3.0, 'attendance_pct': 84.9, 'math_score': 78.0, 'reading_score': 85.0, 'final_score': 40.9}
Row 51 Before: {'gender': 'female', 'study_hours': 1.7, 'attendance_pct': 86.9, 'math_score': 86.0, 'reading_score': 75.0, 'final_score': 40.8}
Row 51 After: {'gender': 'female', 'study_hours': 1.7, 'attendance_pct': 86.9, 'math_score': 86.0, 'reading_score': 75.0, 'final_score': 40.8}
Row 52 Before: {'gender': nan, 'study_hours': 3.9, 'attendance_pct': 91.1, 'math_score': 60.0, 'reading_score': 68.0, 'final_score': 34.7}
Row 52 After: {'gender': 'Unknown', 'study_hours': 3.9, 'attendance_pct': 91.1, 'math_score': 60.0, 'reading_score': 68.0, 'final_score': 34.7}
Row 53 Before: {'gender': 'femle', 'study_hours': 3.8, 'attendance_pct': 81.5, 'math_score': 57.0, 'reading_score': 78.0, 'final_score': 35.0}
Row 53 After: {'gender': 'femle', 'study_hours': 3.8, 'attendance_pct': 81.5, 'math_score': 57.0, 'reading_score': 78.0, 'final_score': 35.0}
Row 54 Before: {'gender': 'female', 'study_hours': 3.5, 'attendance_pct': 91.1, 'math_score': 62.0, 'reading_score': 74.0, 'final_score': 36.3}
Row 54 After: {'gender': 'female', 'study_hours': 3.5, 'attendance_pct': 91.1, 'math_score': 62.0, 'reading_score': 74.0, 'final_score': 36.3}
Row 55 Before: {'gender': nan, 'study_hours': 3.2, 'attendance_pct': 300.0, 'math_score': 51.0, 'reading_score': 82.0, 'final_score': 56.6}
Row 55 After: {'gender': 'Unknown', 'study_hours': 3.2, 'attendance_pct': 300.0, 'math_score': 51.0, 'reading_score': 82.0, 'final_score': 56.6}
Row 56 Before: {'gender': 'male', 'study_hours': 1.8, 'attendance_pct': 88.4, 'math_score': 72.0, 'reading_score': 88.0, 'final_score': 40.8}
Row 56 After: {'gender': 'male', 'study_hours': 1.8, 'attendance_pct': 88.4, 'math_score': 72.0, 'reading_score': 88.0, 'final_score': 40.8}
Row 57 Before: {'gender': 'male', 'study_hours': 3.0, 'attendance_pct': 85.5, 'math_score': 64.0, 'reading_score': 61.0, 'final_score': 33.4}
Row 57 After: {'gender': 'male', 'study_hours': 3.0, 'attendance_pct': 85.5, 'math_score': 64.0, 'reading_score': 61.0, 'final_score': 33.4}
Row 58 Before: {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 82.8, 'math_score': 88.0, 'reading_score': 44.0, 'final_score': 34.8}
Row 58 After: {'gender': 'male', 'study_hours': 3.1, 'attendance_pct': 82.8, 'math_score': 88.0, 'reading_score': 44.0, 'final_score': 34.8}
Row 59 Before: {'gender': 'male', 'study_hours': nan, 'attendance_pct': 80.2, 'math_score': 51.0, 'reading_score': 68.0, 'final_score': 31.7}
Row 59 After: {'gender': 'male', 'study_hours': 3.4134615384615383, 'attendance_pct': 80.2, 'math_score': 51.0, 'reading_score': 68.0, 'final_score': 31.7}