# Supervised Learning

## Linear Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('sales_data.csv')
data.head()

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000

In [6]:
x=data[['Advertising_Spend']]
y=data['Sales_Revenue']

In [8]:
model = LinearRegression()
model.fit(x,y)
print('Training done')

Training done

In [14]:
new_spend=float(input('Enter new spend to predict sales Revenue'))
predicted_revenue = model.predict([[new_spend]])
print(f'New Spend {new_spend} Predicted Revenue {predicted_revenue}')

Enter new spend to predict sales Revenue 78988

New Spend 78988.0 Predicted Revenue [418973.14285714]

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [16]:
#1: collecting the data
df=pd.read_csv('sales_data.csv')
df.head(2)

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000

In [17]:
#2. splitting the data
adv_spend=df[['Advertising_Spend']]
sales_rev=df['Sales_Revenue']

In [20]:
#3. model_creation
model = LinearRegression()

In [25]:
#4. train the model
model.fit(adv_spend,sales_rev)
print('Trained successfully!')

Trained successfully!

In [28]:
#5. predict the outcome
predicted_value=model.predict([[4000]])
print(f'New Spend {adv_spend} Predicted Revenue {predicted_value}')

New Spend    Advertising_Spend
0               1000
1               1500
2               2000
3               2500
4               3000
5               3500
6               4000 Predicted Revenue [27964.28571429]

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# Exercise 1: Predict the data using Linear Regression - House Price Prediction
## Download house_price.csv file from github
##

In [29]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [86]:
df = pd.read_csv('house_price.csv')  # reload the original file
df = df.replace('?', np.nan)
df = df.dropna(subset=['Price'])
df.head()

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000

In [87]:
x=df[['Size_sqft']]
y=df['Price']

In [88]:
model=LinearRegression()

In [ ]:
model.fit(x,y)

In [66]:
new_size=float(input('Enter your desired house size:'))
predicted_price=model.predict([[new_size]])
print(f'With house size {new_size}, the price is {predicted_price}')

Enter your desired house size: 50000

With house size 50000.0, the price is [5408617.64705882]

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(